# Generated by Django 5.0.7 on 2024-07-23 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_user_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 23, 3, 20, 56, 825560, tzinfo=datetime.timezone.utc)),
        ),
    ]
