# Generated by Django 5.0.7 on 2024-07-25 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 25, 15, 32, 39, 981504, tzinfo=datetime.timezone.utc)),
        ),
    ]
