# Generated by Django 5.0.7 on 2024-07-25 16:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_user_loginuser_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 25, 16, 7, 38, 827107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviedatabase'),
        ),
    ]
