# Generated by Django 5.0.7 on 2024-07-26 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_user_date_alter_user_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loginuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 41, 31, 421953, tzinfo=datetime.timezone.utc)),
        ),
    ]
